info:
  contact: {}
paths:
  /api/hello_world:
    get:
      consumes:
      - application/json
      description: do hello
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: hello example
      tags:
      - example
swagger: "2.0"
