definitions:
  request.AdminCreateProject:
    properties:
      description:
        type: string
      name:
        type: string
      owner_id:
        type: integer
    required:
    - description
    - name
    - owner_id
    type: object
  request.AdminRegister:
    properties:
      name:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - name
    - password
    type: object
  request.AdminUpdatePassword:
    properties:
      id:
        type: integer
      password:
        minLength: 8
        type: string
    required:
    - id
    - password
    type: object
  request.UserLogin:
    properties:
      name:
        default: admin
        type: string
      password:
        default: Aa123456
        type: string
      use_mobile:
        type: boolean
    required:
    - name
    - password
    type: object
  request.UserUpdate:
    properties:
      avatar:
        maximum: 20
        minimum: 0
        type: integer
      email:
        type: string
      user_name:
        type: string
    required:
    - avatar
    - email
    - user_name
    type: object
  request.UserUpdatePassword:
    properties:
      new_password:
        minLength: 8
        type: string
      new_password2:
        minLength: 8
        type: string
      old_password:
        type: string
    required:
    - new_password
    - new_password2
    - old_password
    type: object
  response.CommonResponse:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  response.CommonResponseWithoutData:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  response.User:
    properties:
      avatar:
        type: integer
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      user_name:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin/create_project:
    post:
      consumes:
      - application/json
      description: admin create_project
      parameters:
      - description: AdminCreateProject
        in: body
        name: AdminCreateProject
        required: true
        schema:
          $ref: '#/definitions/request.AdminCreateProject'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/response.CommonResponseWithoutData'
      summary: admin create_project
      tags:
      - Admin
  /admin/register:
    post:
      consumes:
      - application/json
      description: admin register
      parameters:
      - description: AdminRegister
        in: body
        name: AdminRegister
        required: true
        schema:
          $ref: '#/definitions/request.AdminRegister'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/response.CommonResponseWithoutData'
      summary: admin register
      tags:
      - Admin
  /admin/update_password:
    post:
      consumes:
      - application/json
      description: admin update_password
      parameters:
      - description: AdminUpdatePassword
        in: body
        name: AdminUpdatePassword
        required: true
        schema:
          $ref: '#/definitions/request.AdminUpdatePassword'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/response.CommonResponseWithoutData'
      summary: admin update_password
      tags:
      - Admin
  /admin/user_list:
    get:
      consumes:
      - '*/*'
      description: admin user_list
      parameters:
      - default: 1
        in: query
        minimum: 1
        name: page
        required: true
        type: integer
      - default: 10
        in: query
        minimum: 5
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: admin user_list
      tags:
      - Admin
  /hello_world:
    get:
      consumes:
      - application/json
      description: do hello
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: hello example
      tags:
      - example
  /user/info:
    get:
      consumes:
      - application/json
      description: user info
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            allOf:
            - $ref: '#/definitions/response.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.User'
              type: object
      summary: user info
      tags:
      - User
  /user/login:
    post:
      consumes:
      - application/json
      description: user login
      parameters:
      - description: UserRegister
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/response.CommonResponseWithoutData'
      summary: user login
      tags:
      - User
  /user/logout:
    post:
      consumes:
      - application/json
      description: user logout
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/response.CommonResponseWithoutData'
      summary: user logout
      tags:
      - User
  /user/update:
    post:
      consumes:
      - application/json
      description: user update1
      parameters:
      - description: UserUpdate
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.UserUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/response.CommonResponseWithoutData'
      summary: user update
      tags:
      - User
  /user/update_password:
    post:
      consumes:
      - application/json
      description: user update_password
      parameters:
      - description: UserUpdatePassword
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.UserUpdatePassword'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/response.CommonResponseWithoutData'
      summary: user update_password
      tags:
      - User
swagger: "2.0"
