#!/bin/bash

# 获取所有已添加到暂存区的 Go 文件
staged_go_files=$(git diff --cached --name-only -- '*.go')

if [ -n "$staged_go_files" ]; then
    # 使用 gofumpt 格式化这些文件
    for file in $staged_go_files; do
        gofumpt -w "$file"
        # 将格式化后的文件重新添加到暂存区
        git add "$file"
    done
fi


swag init -g cmd/server/main.go -d  server -o server/docs 
git add server/docs

# 重新add 这些文件
files=$(git diff --cached --name-only -- 'font/*')
if [ -n "$files" ]; then
    echo "Files to format: $files"  # 输出文件路径进行调试
    # 对这些文件进行格式化
    npx prettier "${files[@]}" --write
    # 检查是否有文件被修改
    modified_files=$(git diff --name-only -- 'font/*')
    if [ -n "$modified_files" ]; then
        echo "Modified files after formatting: $modified_files"
        git add "$modified_files"
    else
        echo "No files were modified after formatting."
    fi
fi

exit 0    