#!/bin/bash

# 获取所有已添加到暂存区的 Go 文件
staged_go_files=$(git diff --cached --name-only -- '*.go')

if [ -n "$staged_go_files" ]; then
    # 使用 gofumpt 格式化这些文件
    for file in $staged_go_files; do
        gofumpt -w "$file"
        # 将格式化后的文件重新添加到暂存区
        git add "$file"
    done
fi


swag init -g cmd/server/main.go -d  server -o server/docs 
git add server/docs

# 重新add 这些文件
files=$(git diff --cached --name-only -- 'font/*')
if [ -n "$files" ]; then
  # 对这些文件进行格式化
  npx prettier "${files[@]}" --write
  # 重新 add 这些文件
  git add "${files[@]}"
fi

exit 0    